
### подучить cycle 1
GET localhost:8080/api/cycle/1

###  все по юзеру
GET localhost:8080/api/cycle/all/0


###  все по юзеру 1
GET localhost:8080/api/cycle/all/1

### все ПОЛНЫЕ по юзеру
GET localhost:8080/api/cycle/full/1

### все темплейты
GET localhost:8080/api/cycle/templates

### темплейт по id
GET localhost:8080/api/cycle/templates/1

###  сохранить новую
POST localhost:8080/api/cycle
Content-Type: application/json

{
  "workoutList": [],
  "isDefaultType": true,
  "image": "",
  "imageDefault": "plint14",
  "id": 0,
  "title": "Плинтович (Фаза 1)",
  "startDate": "2017-12-31T21:00:00.000+00:00",
  "finishDate": "2018-02-13T21:00:00.000+00:00",
  "comment": "Тренировки следует проводить три раза в неделю по схеме Пн, Ср, Пт или Вт, Чт, Сб.\nПервая фаза состоит только из одного тренировочного дня, который повторяется все три тренировки в неделю. Все три тренировки в неделю на первой фазе будут с одним и тем же ",
  "parentId": 0,
  "startStringFormatDate": "2018-01-01",
  "finishStringFormatDate": "2018-02-14"
}

### внести изменение в
PUT localhost:8080/api/cycle
Content-Type: application/json

{
  "workoutList": [],
  "isDefaultType": true,
  "image": "",
  "imageDefault": "update",
  "id": 6024,
  "title": "update",
  "startDate": "2017-12-31T21:00:00.000+00:00",
  "finishDate": "2018-02-13T21:00:00.000+00:00",
  "comment": "update",
  "parentId": 0,
  "startStringFormatDate": "2018-01-01",
  "finishStringFormatDate": "2018-02-14"
}

### удаление по id
DELETE localhost:8080/api/cycle/652
Content-Type: application/json
